version: '3'
services:
  su_admin_api:
    build: .
    image: su_admin_api
    container_name: su_admin_api
    restart: always
    ports:
    - "7080:8080"
    environment:
    - "SPRING_PROFILES_ACTIVE=test"
    #- "SPRING_CONFIG_LOCATION=/customs/"